env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  pg_user: "postgres"
  pg_database: "postgres"
  pg_host: "localhost"
  pg_port: "5436"
  pg_sslmode: "disable"
  pg_password: "qwerty"
clients:
  triggerHookService:
    address: "127.0.0.1:44044"
    timeout: 5s
    retriesCount: 3
